name: 💬 Feedback
description: Let us know your opinion about Marc Bernard Tools
title: "Feedback: "
labels: ["feedback"]
body:
  - type: markdown
    attributes:
      value: |
        Anything goes! The good, the bad, and the ugly. Just keep it decent since your post will be public.
  
  - type: textarea
    id: version
    attributes:
      label: Version
      description: Version of the tool
      placeholder: |
        Version: 1.x.y
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Your Feedback
    validations:
      required: true
