name: 💭 Question
description: Do you have a question about Marc Bernard Tools?
title: "Q: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Any question about Marc Bernard Tools? Let us know. We are here to help!
  
  - type: textarea
    id: description
    attributes:
      label: Your Question
    validations:
      required: true
