name: 💬 Question
description: Do you have a question about Marc Bernard Tools?
labels: ["question"]
title: ""
body:
  - type: markdown
    attributes:
      value: |
        Any question about Marc Bernard Tools? Let us know. We are here to help!
  
  - type: textarea
    id: version
    attributes:
      label: Version
      description: Name and version of the tool
      placeholder: |
        Name: MBT '...'
        Version: 1.x.y
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Your Question
    validations:
      required: true
